### PR TITLE
Added the discordCommandManager

### PR DESCRIPTION
**Pull request by JuliaSoriaSmith**
I have added a command manager to set the application commands globally or by guild, as well as delete commands globally by guild. 

Minor modification as made to the bot manager to get the ID and token for the push command. 

Setting commands can be done by using msg.commands, e.g.

var pingCommand = new SlashCommandBuilder()
	.setName('bloop')
	.setDescription('Replies with bloop!');

msg.commands = [ pingCommand ]

msg.action = "set"

Deleting commands can be done by setting the commandId, e.g.

msg.action = "delete"
msg.commandId = "181512451821"

It respects msg.guild, so it can delete/set per guild or globally if msg.guild is not set.

### CODE REVIEW

**Comment by javis86** [comment]
@JuliaSoriaSmith in order to use this approach, will It be needed to have installed the discord.js package, like It has been working until now? Because I has been thinking a lot about it. 
The current approach was created as a quick solution, but for future work like you has done now.
I will test it this weekend
thxs

**Comment by JuliaSoriaSmith** [comment]
Yes it will need discord.js, it depends upon it similar to other nodes. Do you want to move away from discord.js?

**Comment by javis86** [comment]
Installing discord.js for function nodes can be lead to mismatching versions between function node  and node-red-contrib-discord-advanced versions.
The suitable options that i was thinking about are:

- discord js commands as strings
```js
var pingCommand = "new SlashCommandBuilder().setName(\'bloop\').setDescription(\'Replies with bloop!\');"
```
- A full node  for designing commands, with a nice editor (The best options but it takes some time to code it)

I think we can deploy a npm version with your approach and then, with more time, to improve it.

**Comment by javis86** [comment]
I have working an example.

image
image
image

After the changes committed, we need to create a entry on wiki to explain how the node works and to add some flows examples

**Comment by javis86** [comment]
This also works

```js
var pingCommand = {
    name: "bloop",
    description: "Replies with bloop!"
};


msg.commands =  pingCommand;

msg.action = "set";
return msg;
```
This example is using json format for commands creation
https://discord.com/developers/docs/interactions/application-commands#making-a-global-command

**Pull request merged**
